# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\"\x15\n\x04Hand\x12\r\n\x05value\x18\x01 \x01(\t\"\x06\n\x04void2C\n\x08\x41nalizer\x12\x1a\n\x08SendHand\x12\x05.Hand\x1a\x05.void\"\x00\x12\x1b\n\tgetWinner\x12\x05.void\x1a\x05.Hand\"\x00\x62\x06proto3')



_HAND = DESCRIPTOR.message_types_by_name['Hand']
_VOID = DESCRIPTOR.message_types_by_name['void']
Hand = _reflection.GeneratedProtocolMessageType('Hand', (_message.Message,), {
  'DESCRIPTOR' : _HAND,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:Hand)
  })
_sym_db.RegisterMessage(Hand)

void = _reflection.GeneratedProtocolMessageType('void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:void)
  })
_sym_db.RegisterMessage(void)

_ANALIZER = DESCRIPTOR.services_by_name['Analizer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HAND._serialized_start=14
  _HAND._serialized_end=35
  _VOID._serialized_start=37
  _VOID._serialized_end=43
  _ANALIZER._serialized_start=45
  _ANALIZER._serialized_end=112
# @@protoc_insertion_point(module_scope)
